# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: post
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


production:
  database: pims
  adapter: postgresql
  encoding: utf8
  reconnect: true
  timeout: 5000
  pool: 5
  username: postgres
  password: postgres
  host: localhost
